In [1]:
 # Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [29]:
# Read Population-EstimatesData into pandas
pop_df=pd.read_csv('/Users/mikan/Documents/Data Science Bootcamp/populations_project/Population-EstimatesData.csv')
pop_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050
0,Arab World,ARB,Age dependency ratio (% of working-age populat...,SP.POP.DPND,88.061110,89.489513,90.782451,91.898948,92.728007,93.201290,...,54.244434,54.356396,54.502067,54.676725,54.874161,55.102246,55.331887,55.562180,55.789065,56.009450
1,Arab World,ARB,"Age dependency ratio, old",SP.POP.DPND.OL,6.591951,6.700903,6.793279,6.867327,6.919224,6.947790,...,12.973244,13.345549,13.732773,14.132766,14.544481,14.946251,15.349197,15.755873,16.168726,16.589418
2,Arab World,ARB,"Age dependency ratio, young",SP.POP.DPND.YG,81.324186,82.626198,83.789155,84.767354,85.474209,85.872972,...,40.757181,40.542064,40.345297,40.162781,39.987572,39.845466,39.699291,39.546177,39.380479,39.197560
3,Arab World,ARB,"Age population, age 00, female, interpolated",SP.POP.AG00.FE.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,"Age population, age 00, male, interpolated",SP.POP.AG00.MA.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
# Select the necessary rows and columns
# Rows - European Union, Central Europe and the Baltics, Sub Saharan Africa, United States, Latin America and Caribbean, 
# Middle East and North Africa, East Asia and Pacific, South Asia, World
# Columns Country Name, Country Code, Indicator Name, Indicator Code, 1970 - 2050

pop_df=pop_df.rename(columns={'Country Name':'Country_Name',
                     'Country Code':'Country_Code',
                     'Indicator Name':'Indicator_Name',
                     'Indicator Code':'Indicator_Code'})
pop_df.head()

# Delete the rows with many NaN
pop_df=pop_df.dropna()
pop_df.head(10)

,Country_Name,Country_Code,Indicator_Name,Indicator_Code,1960,1961,1962,1963,1964,1965,...,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050
0,Arab World,ARB,Age dependency ratio (% of working-age populat...,SP.POP.DPND,8.806111e+01,8.948951e+01,9.078245e+01,9.189895e+01,9.272801e+01,9.320129e+01,...,5.424443e+01,5.435640e+01,5.450207e+01,5.467672e+01,5.487416e+01,5.510225e+01,5.533189e+01,5.556218e+01,5.578906e+01,5.600945e+01
1,Arab World,ARB,"Age dependency ratio, old",SP.POP.DPND.OL,6.591951e+00,6.700903e+00,6.793279e+00,6.867327e+00,6.919224e+00,6.947790e+00,...,1.297324e+01,1.334555e+01,1.373277e+01,1.413277e+01,1.454448e+01,1.494625e+01,1.534920e+01,1.575587e+01,1.616873e+01,1.658942e+01
2,Arab World,ARB,"Age dependency ratio, young",SP.POP.DPND.YG,8.132419e+01,8.262620e+01,8.378916e+01,8.476735e+01,8.547421e+01,8.587297e+01,...,4.075718e+01,4.054206e+01,4.034530e+01,4.016278e+01,3.998757e+01,3.984547e+01,3.969929e+01,3.954618e+01,3.938048e+01,3.919756e+01
75,Arab World,ARB,"Population ages 00-04, female",SP.POP.0004.FE,8.051199e+06,8.272433e+06,8.506654e+06,8.756934e+06,9.015470e+06,9.283968e+06,...,2.716000e+07,2.734400e+07,2.749800e+07,2.763600e+07,2.776000e+07,2.788000e+07,2.798800e+07,2.808600e+07,2.815600e+07,2.820800e+07
76,Arab World,ARB,"Population ages 00-04, female (% of female pop...",SP.POP.0004.FE.5Y,1.761132e+01,1.761248e+01,1.762480e+01,1.765258e+01,1.767792e+01,1.770346e+01,...,9.234130e+00,9.174653e+00,9.107935e+00,9.037413e+00,8.965592e+00,8.895500e+00,8.823611e+00,8.749806e+00,8.672858e+00,8.591927e+00
77,Arab World,ARB,"Population ages 00-04, male",SP.POP.0004.MA,8.366535e+06,8.616678e+06,8.868385e+06,9.126749e+06,9.391460e+06,9.669589e+06,...,2.837900e+07,2.857300e+07,2.873200e+07,2.887100e+07,2.899700e+07,2.912900e+07,2.924200e+07,2.933700e+07,2.941700e+07,2.946900e+07
78,Arab World,ARB,"Population ages 00-04, male (% of male populat...",SP.POP.0004.MA.5Y,1.799963e+01,1.804337e+01,1.807322e+01,1.809891e+01,1.811825e+01,1.814357e+01,...,9.153368e+00,9.104658e+00,9.048119e+00,8.987363e+00,8.925352e+00,8.865278e+00,8.802738e+00,8.737748e+00,8.669298e+00,8.596831e+00
79,Arab World,ARB,Population ages 0-14 (% of total population),SP.POP.0014.TO.ZS,4.327685e+01,4.364203e+01,4.396478e+01,4.423383e+01,4.442678e+01,4.453513e+01,...,2.651214e+01,2.634529e+01,2.618500e+01,2.602975e+01,2.587653e+01,2.574132e+01,2.560441e+01,2.546406e+01,2.531703e+01,2.516097e+01
80,Arab World,ARB,"Population ages 0-14, female",SP.POP.0014.FE.IN,1.950100e+07,2.020432e+07,2.092148e+07,2.164437e+07,2.235622e+07,2.304805e+07,...,7.838100e+07,7.887900e+07,7.937600e+07,7.987000e+07,8.035100e+07,8.086900e+07,8.136900e+07,8.183800e+07,8.226000e+07,8.263300e+07
81,Arab World,ARB,"Population ages 0-14, female (% of female popu...",SP.POP.0014.FE.ZS,4.265679e+01,4.301615e+01,4.334689e+01,4.363157e+01,4.383702e+01,4.394996e+01,...,2.664695e+01,2.646491e+01,2.628985e+01,2.611968e+01,2.595136e+01,2.580143e+01,2.565097e+01,2.549740e+01,2.533714e+01,2.516774e+01

In [47]:
# Select the necessary regions under Country_Name
# #reference : https://cmdlinetips.com/2018/02/how-to-subset-pandas-dataframe-based-on-values-of-a-column/

names = ['European Union', 'Central Europe and the Baltics', 'Sub Saharan Africa', 'United States'
        'Latin America and Caribbean', 'Middle East and North Africa', 'East Asia and Pacific', 'South Asia','World']

pop_df1= pop_df[pop_df.Country_Name.isin(names)]
pop_df1

,Country_Name,Country_Code,Indicator_Name,Indicator_Code,1960,1961,1962,1963,1964,1965,...,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050
350,Central Europe and the Baltics,CEB,Age dependency ratio (% of working-age populat...,SP.POP.DPND,5.741188e+01,5.752730e+01,5.728712e+01,5.677139e+01,5.614491e+01,5.551517e+01,...,6.521464e+01,6.646455e+01,6.776753e+01,6.906237e+01,7.031534e+01,7.158719e+01,7.275529e+01,7.386537e+01,7.498979e+01,7.617579e+01
351,Central Europe and the Baltics,CEB,"Age dependency ratio, old",SP.POP.DPND.OL,1.134335e+01,1.164324e+01,1.195043e+01,1.225932e+01,1.256735e+01,1.287642e+01,...,4.318770e+01,4.425557e+01,4.535228e+01,4.642422e+01,4.744606e+01,4.845903e+01,4.936855e+01,5.021531e+01,5.107022e+01,5.198438e+01
352,Central Europe and the Baltics,CEB,"Age dependency ratio, young",SP.POP.DPND.YG,4.587778e+01,4.567246e+01,4.512306e+01,4.431009e+01,4.339136e+01,4.246881e+01,...,2.198657e+01,2.217074e+01,2.237985e+01,2.260623e+01,2.284224e+01,2.310576e+01,2.336620e+01,2.362480e+01,2.388381e+01,2.414218e+01
425,Central Europe and the Baltics,CEB,"Population ages 00-04, female",SP.POP.0004.FE,4.464694e+06,4.330142e+06,4.166955e+06,3.997629e+06,3.856297e+06,3.756717e+06,...,1.952000e+06,1.955000e+06,1.956000e+06,1.954000e+06,1.954000e+06,1.953000e+06,1.949000e+06,1.944000e+06,1.936000e+06,1.927000e+06
426,Central Europe and the Baltics,CEB,"Population ages 00-04, female (% of female pop...",SP.POP.0004.FE.5Y,9.467271e+00,9.105751e+00,8.695317e+00,8.273413e+00,7.911588e+00,7.652383e+00,...,4.136009e+00,4.166504e+00,4.193251e+00,4.217808e+00,4.240919e+00,4.265988e+00,4.286188e+00,4.301934e+00,4.313000e+00,4.318730e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7341,World,WLD,"Population, total",SP.POP.TOTL,3.032020e+09,3.073078e+09,3.126066e+09,3.191186e+09,3.256700e+09,3.323624e+09,...,9.199039e+09,9.256312e+09,9.312513e+09,9.367581e+09,9.421505e+09,9.474243e+09,9.525803e+09,9.576173e+09,9.625330e+09,9.672918e+09
7343,World,WLD,Rural population,SP.RUR.TOTL,2.012352e+09,2.023831e+09,2.044913e+09,2.075168e+09,2.104985e+09,2.140904e+09,...,3.235480e+09,3.219443e+09,3.202834e+09,3.185328e+09,3.166992e+09,3.147815e+09,3.127848e+09,3.107097e+09,3.085577e+09,3.063240e+09
7344,World,WLD,Rural population (% of total population),SP.RUR.TOTL.ZS,6.639084e+01,6.587759e+01,6.543578e+01,6.504902e+01,6.465645e+01,6.443573e+01,...,3.517990e+01,3.478896e+01,3.440054e+01,3.401138e+01,3.362206e+01,3.323255e+01,3.284290e+01,3.245340e+01,3.206399e+01,3.167519e+01
7347,World,WLD,Urban population,SP.URB.TOTL,1.018717e+09,1.048277e+09,1.080155e+09,1.114992e+09,1.150661e+09,1.181637e+09,...,5.961460e+09,6.034775e+09,6.107564e+09,6.180133e+09,6.252385e+09,6.324286e+09,6.395817e+09,6.466923e+09,6.537604e+09,6.607533e+09
7348,World,WLD,Urban population (% of total population),SP.URB.TOTL.IN.ZS,3.360916e+01,3.412241e+01,3.456422e+01,3.495098e+01,3.534355e+01,3.556427e+01,...,6.482010e+01,6.521104e+01,6.559946e+01,6.598862e+01,6.637794e+01,6.676745e+01,6.715710e+01,6.754660e+01,6.793601e+01,6.832481e+01